project:
  type: website

website:
  title: "Image2025"
  navbar:
    left:
      - href: index.qmd
        text: Home
    right:
      - icon: github
        href: https://github.com/slimgroup
  sidebar:
      style: "docked"
      search: true
      contents:
      - section: "Abstracts"
        contents:
        - file: Gahlot2025SEG/paper.qmd
          text: "Enhancing robustness of Digital Shadow"
    center:
      - file: license.qmd
        text: "2025 Copyright (c) SLIM @ Georgia Institute of Technology"

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    lightbox: True
    toc: true
    link-external-newwindow: True

execute:
  freeze: auto
